services:
  db:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aq
    volumes:
      - db-data:/var/lib/postgresql/data
    command: >
      postgres -c shared_preload_libraries=timescaledb

  api:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

volumes:
  db-data:
